# Generated by Django 5.0.7 on 2024-08-04 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_healthcaredetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcaredetails',
            name='fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_healthcare', to='api_app.patient'),
        ),
    ]
